package com.example.cv_translater;

public class BolumArrayi {
    public String[] okulbolumu = {
            "Bolum Secilmedi",
            "Rettungssanitäter",
            "Nothilfe und Katastrophenmanagement",
            "Forensische Technik",
            "Netzwerk Management",
            "Wood Works Industrial Engineering",
            "Holzschreinertechnik",
            "Holzbausysteme",
            "Familienökonomie und Ernährungsunterricht",
            "Familien- und Verbraucherwissenschaften",
            "Familien- und Verbraucherwissenschaft Bildung",
            "Zubehördesign",
            "Aktuar",
            "Aktuarwissenschaften",
            "Versicherungsmathematisches und Risikomanagement",
            "Gipsmodellform",
            "Deutsche Sprache und Literatur",
            "Deutschunterricht",
            "Amerikanische Kultur und Literatur",
            "Anästhesietechniker",
            "Animation",
            "Animator",
            "Trainertraining",
            "Anthropologie",
            "Arabische Sprache und Literatur",
            "Arabischunterricht",
            "Archäologie",
            "Archäologie",
            "Archäologie und Kunstgeschichte",
            "Albanische Sprache und Literatur",
            "Harfe",
            "Astronomie und Weltraumwissenschaften",
            "Beziehungen zur Europäischen Union",
            "Schuhmodellierung",
            "Schuhproduktion",
            "Aserbaidschan Türkisch und Literatur",
            "Gartenpflanzen",
            "Ballett",
            "Balletttanzen",
            "Kapitän des Fischereifahrzeugs",
            "Fischereitechnik",
            "Fischereitechnik",
            "Bandchef",
            "Bankgeschäfte",
            "Banken und Finanzen",
            "Banken und Versicherungen",
            "Bar",
            "Drucktechnologien",
            "Presse und Veröffentlichung",
            "Druckvorstufe",
            "Nach dem Drucken",
            "Druckkunst",
            "Sportunterricht und Sportunterricht",
            "Lebensmitteltechnologie",
            "Ernährung und Diätetik",
            "Gebäude aus Stahlbeton",
            "Beton Zement- und Bodentechnologie",
            "Zusammengesetzte Künste",
            "Informations- und Dokumentenverwaltung",
            "Computergestützte industrielle Modellierung",
            "Computer Aided Machine Painting",
            "Technischer Computerdienst",
            "Informatik und Ingenieurwesen",
            "Informatik",
            "Technische Informatik",
            "Computerunterricht",
            "Unterricht in Computersystemen",
            "Computertechnologie und Informationssysteme",
            "Computer- und Steuerungsunterricht",
            "Lehrerausbildung für Computer- und Unterrichtstechnologie",
            "Computer- und Softwareentwicklung",
            "Computergestützte Maschinenherstellung",
            "Computergestützte Buchhaltung",
            "Wissenschaftsgeschichte",
            "Informationssystemtechnik",
            "Informationssysteme und Technologien",
            "Pflanzenschutz",
            "Pflanzenproduktion",
            "Pflanzenproduktion und Technologien",
            "Bioinformatik und Genetik",
            "Biochemie",
            "Biologie",
            "Biologieunterricht",
            "Biomedizintechnik",
            "Bioengineering",
            "Biosystemtechnik",
            "Biotechnologie",
            "Biotechnologie und Molekularbiologie",
            "Spule",
            "Bosnische Sprache und Literatur",
            "Lackherstellung und -anwendung",
            "Bulgarische Sprache und Literatur",
            "Technischer Service für Büromaschinen",
            "Lehrer für Büromanagement",
            "Kiefer",
            "Design und Management von Animationsfilmen",
            "Jazz",
            "Fassadensysteme und PVC-Tischlerei",
            "Aufbereitungstechnik",
            "Hautpflege",
            "Erdkunde",
            "Geographieunterricht",
            "Zeitgenössische türkische Dialekte und Literaturen",
            "Zeitgenössische griechische Sprache und Literatur",
            "Instrument",
            "Instrumentenausbildung",
            "Instrumentenbau",
            "Arbeitsökonomie und Arbeitsbeziehungen",
            "Teeproduktion und -verarbeitung",
            "Stahlschiffbau",
            "Stahlkonstruktion",
            "Technische Zeichnung für Stahlkonstruktionen",
            "Circassianische Sprache und Literatur",
            "Übersetzungswissenschaft (Deutsch)",
            "Übersetzungswissenschaft (Englisch)",
            "Umweltdienstleistungen",
            "Umweltgesundheitstechniker",
            "Umwelttechnik",
            "Blumen arrangement",
            "Blumen-, Strick- und Webunterricht",
            "Chinesische Sprache und Literatur",
            "Fliese",
            "Fliesendesign",
            "Fliesen",
            "Cartoon und Animation",
            "Kinderanimator",
            "Modellierung von Kinderbekleidung",
            "Entwicklung des Kindes",
            "Kinderentwicklung und Vorschulunterricht",
            "Anleitung zur Gesundheit und Entwicklung von Kindern (Pdr)",
            "Tanzen",
            "dekoratives Glas",
            "Dekoratives Kunsthandwerk",
            "Dekorative Heimtextilien",
            "Dekorative Kunst",
            "Unterricht in dekorativer Kunst",
            "Meerestechnik",
            "Schiffsverkehrsmanagement",
            "Maritime Unternehmensführung",
            "Leder Kleidung",
            "Lederverarbeitung",
            "Ledertechnik",
            "Pflanzen im Freien",
            "Dienstleistungen des Außenhandelsbüros",
            "Sprach- und Sprachtherapie",
            "Linguistik",
            "Religiöse Kultur und moralische Erziehung",
            "Zahnprothetiker",
            "Zahnarzt",
            "Webdesign",
            "Weboperator",
            "Vliesoberflächen",
            "Casting",
            "Gießereilehrer",
            "Drama und Schauspiel",
            "Dramatisches Schreiben",
            "Dramatische Schreib-Dramaturgie",
            "Sensorisches (Audio-) Kunstdesign",
            "Weltreligionen",
            "Geburtshilfe",
            "Apotheke",
            "Ökonometrie",
            "Wirtschaft",
            "Politische Ökonomie und Sozialphilosophie",
            "Wirtschaft und Finanzen",
            "Handweberei",
            "Hand- und Maschinenstickerei",
            "Kunsthandwerk",
            "Handwerk Design und Produktion",
            "Elektrische Installationen und Panel-Installation",
            "Elektrotechnik",
            "Elektrizitätsunterricht",
            "Elektrotechnik und Elektronik",
            "Technischer Service für Elektrogeräte",
            "Wartung und Reparatur elektromechanischer Träger",
            "Elektronisches Ingenieurwesen",
            "Elektronischer Unterricht",
            "Elektronik- und Computererziehung",
            "Elektonik-und Kommunikationstechnik",
            "Elektronik- und Kommunikationsunterricht",
            "Immobilienmakler",
            "Wirtschaftsingenieurwesen",
            "Industrielle Systemtechnik",
            "Industrielles Design",
            "Design industrieller Produkte",
            "Industrie- und Systemtechnik",
            "Industrielle Wartung und Reparatur",
            "Industrieglas",
            "Industrielles Sockenstricken",
            "Industrielles Flachstricken",
            "Industrieform",
            "Industrielle Steuerung",
            "Industrieller Gemüse- und Obstanbau",
            "Industrielles Rundstricken",
            "Industrielles Design",
            "Industriedesign",
            "Industrielle Technologieerziehung",
            "Energieunterricht",
            "Energiesystemtechnik",
            "Informationstechnologien",
            "Behindertenhilfe",
            "Sportunterricht und Sportunterricht für behinderte Menschen",
            "Beschäftigungstherapie",
            "Modellierung von Herrenbekleidung",
            "Herrenschneiderei",
            "Frühkindliche Erziehung",
            "Armenische Sprache und Literatur",
            "Alte Fliesenreparaturen",
            "Altgriechische Sprache und Literatur",
            "Ethnologie",
            "Heim- und institutionelle Dienstleistungen",
            "Hauswirtschaft",
            "Fagott",
            "Persische Sprache und Literatur",
            "Philosophie",
            "Philosophiegruppenunterricht",
            "Naturwissenschafts-Lehrer",
            "Wissenschaft",
            "Filmdesign und Schreiben",
            "Filmdesign und Regie",
            "Filmdesign",
            "Finanz- und Börsendienste",
            "Finanzmathematik",
            "Physik",
            "Physikingenieurwesen",
            "Physikunterricht",
            "Physiotherapie und Rehabilitation",
            "Physiologische Signalüberwachung, Diagnose und Rekorder",
            "Flexodruck",
            "Flöte",
            "Fotojournalismus",
            "Foto",
            "Foto",
            "Fotografie und Grafik",
            "Foto und Video",
            "Französische Sprache und Literatur",
            "Französischlehrer",
            "Faire Organisation verantwortlich",
            "Gastronomie",
            "Gastronomie und Kochkunst",
            "Immobilien- und Vermögensbewertung",
            "Journalismus",
            "Traditionelles türkisches Kunsthandwerk",
            "Traditionelle türkische Musik",
            "Traditionelle türkische Kunst",
            "Schiffselektronik und Kommunikation",
            "Schiffsautomatisierung",
            "Schiffsmalerei",
            "Schiffsinstallationsausrüstung",
            "Schiffsmanagement",
            "Schiffbau und Schiffsmaschinentechnik",
            "Schiffbautechnik",
            "Schiffbau und Schiffsmaschinentechnik",
            "Schiffsmaschinenmanagement",
            "Schiffs- und Meerestechnik",
            "Schiffs- und Yachtdesign",
            "Allgemeine Musikwissenschaft",
            "Genetik und Bioinformatik",
            "Genetik und Bioengineering",
            "Geomatische Technik",
            "Gerontologie",
            "Lebensmittelkontrolle",
            "Lebensmittelverkaufspersonal",
            "DAS LEBENSMITTELTECHNIK",
            "Lebensmitteltechnologie",
            "Unternehmerschaft",
            "Gitarre",
            "Lehre in der Bekleidungsindustrie",
            "Kleidungsunterricht",
            "Sehbehinderte Lehrerausbildung",
            "Visuelle Kommunikation",
            "Visuelles Kommunikationsdesign",
            "Bildende Kunst",
            "Bildende Kunst und visuelles Kommunikationsdesign",
            "Video- und Soundsysteme",
            "Bildende Kunst",
            "Grafik",
            "Grafik",
            "Grafische Ausbildung",
            "Grafische Darstellung und Druck",
            "Grafik",
            "Grafikdesign",
            "Grafik Animation",
            "Zollgeschäft",
            "Solarenergiesysteme",
            "Georgische Sprache und Literatur",
            "Sicherheitssysteme",
            "Kommunikationssysteme",
            "Teppichgestaltung",
            "Teppich Teppich",
            "Teppich-, Teppich- und alte Stoffmuster",
            "Folklore",
            "Öffentlichkeitsarbeit",
            "Öffentlichkeitsarbeit",
            "Öffentlichkeitsarbeit und Werbung",
            "Öffentlichkeitsarbeit und Werbung",
            "Kartentechnik",
            "Kartographie",
            "Patientenversorgung",
            "Linie",
            "Wetterbeobachtung und -vorhersage",
            "Luftraumüberwachung",
            "Luftfahrtelektrik und Elektronik",
            "Luftverkehrsmanagement",
            "Luft- und Raumfahrttechnik",
            "Luftverkehrsmanagement",
            "Tierproduktion",
            "Bekleidungsmodellmaschinen",
            "Bekleidungserziehung",
            "Pflege",
            "Krankenpflege",
            "Pflege- und Gesundheitsdienste",
            "Statue",
            "Kroatische Sprache und Literatur",
            "Hydrogeologische Technik",
            "Indologie",
            "Hittitologie",
            "Gastgeberin",
            "Getreideverarbeitung",
            "Gesetz",
            "Rechtssekretariat",
            "Hungarologie",
            "Garnherstellungstechnologie",
            "Wärmebehandlung",
            "Hebräische Sprache und Literatur",
            "Modellierung von Unterwäsche",
            "Zimmerpflanzen",
            "Innenausstattung",
            "Technische Innenausarbeitung",
            "Innen- und Möbeltechnik",
            "Innenarchitektur",
            "Innenarchitektur und Umweltdesign",
            "Klimaanlagen",
            "Wirtschaft",
            "Theologie",
            "Kontakt",
            "Kommunikationswissenschaften",
            "Kommunikationskunst",
            "Kommunikationsdesign und -management",
            "Kommunikation und Design",
            "Grundschulbildung Religiöse Kultur und moralische Erziehung",
            "Grundlegende Mathematikausbildung",
            "Fertigungstechnik",
            "Ausführung und Schutz",
            "Englische Sprachwissenschaft",
            "Englische Sprache und Literatur",
            "Englische Sprache und Vergleichende Literaturwissenschaft",
            "Englischlehrer",
            "Englischunterricht Unterricht",
            "Personalmanagement",
            "Human- und Sozialwissenschaften",
            "Bauingenieurwesen",
            "Islam- und Religionswissenschaften",
            "Islamische Wissenschaften",
            "Spanische Sprache und Literatur",
            "Statistiken",
            "Statistik und Informatik",
            "Geschäftsmaschinen",
            "Arbeits-und Gesundheitsschutz",
            "Hörgeschädigte Lehrerausbildung",
            "Geschäft",
            "Geschäftsinformationsmanagement",
            "Wirtschaftsinformatik",
            "Management Engineering",
            "Wirtschaftslehrer",
            "Geschäftsverwaltung",
            "Betriebswirtschaftslehre",
            "Italienische Sprache und Literatur",
            "Brandbekämpfung und Brandschutz",
            "Schmelze",
            "Japanische Sprache und Literatur",
            "Japanischunterricht",
            "Geodäsie- und Photogrammetrietechnik",
            "Geophysikalische Technik",
            "Geologische Technik",
            "Katasteralismus",
            "Modellierung von Damenbekleidung",
            "Schneiderei für Frauen",
            "Formenbauunterricht",
            "Videografie",
            "Öffentliche Verwaltung",
            "Meinungsforschung",
            "Geflügelzucht",
            "Vergleichende Literaturwissenschaft",
            "Vergleichende Literaturwissenschaft (Englisch)",
            "Hauswirtschaft",
            "Schweißen",
            "Violine",
            "Städtebau und Landschaftsarchitektur",
            "Schneiden",
            "Schnittblumen",
            "Chemie",
            "Chemielabor",
            "Chemieingenieurwesen",
            "Chemieingenieurwesen und Angewandte Chemie",
            "Chemieunterricht",
            "Chemie- und Verfahrenstechnik",
            "Chemie-Biotechnik",
            "Klarinette",
            "Klassische Archäologie",
            "Klassisches Ballett",
            "Komposition",
            "Komposition und Orchesterleitung",
            "Zusammensetzung (Zusammensetzung)",
            "Krankenhausverwaltung",
            "Hospitality Management Training",
            "Lehrer für Hotelmanagement",
            "Wartung und Reparatur von Bekleidungsmaschinen",
            "Kontrabass",
            "Steuerungstechnik",
            "Kontrollieren Sie den Unterricht",
            "Steuerungs- und Automatisierungstechnik",
            "Koreanische Sprache und Literatur",
            "Der Koreoloj",
            "Hupe",
            "Chor",
            "Friseur- und Schönheitswissenschaftsausbildung",
            "Bearbeitung von Audio- und Videomanagement",
            "Schmuck",
            "Schmuck und Schmuckdesign",
            "Schutz und Reparatur des kulturellen Erbes",
            "Kulturmanagement",
            "Kulturwissenschaften",
            "Globale Politik und internationale Beziehungen",
            "Globale und internationale Beziehungen",
            "Kurdische Sprache und Literatur",
            "Bibliothekswesen",
            "Reifenproduktion",
            "Lateinische Sprache und Literatur",
            "Polnische Sprache und Literatur",
            "Logistik",
            "Logistik",
            "Logistikverwaltung",
            "Bergbautechnik",
            "Wartung und Reparatur der Maschine",
            "Maschinenoffizier",
            "Maschinenbau",
            "Maschinenlackierung und Konstruktionsunterricht",
            "Maschinenbau und Fertigungstechnik",
            "Bilden",
            "Finanzen",
            "Materialwissenschaft und Werkstofftechnik",
            "Materialwissenschaft und Nanotechnik",
            "Materialwissenschaft und Nanotechnologie",
            "Werkstofftechnik",
            "Druckausbildung",
            "Mathe",
            "Mathematik",
            "Mathematikunterricht",
            "Mathematik und Informatik",
            "Mathematik und Informatik",
            "Medien und Bildende Kunst",
            "Medien und Kommunikation",
            "Medien- und Kommunikationssysteme",
            "Mechatronik",
            "Mechatronik",
            "Mechatronikunterricht",
            "Mechatronik-Systemtechnik",
            "Marmorverarbeitung",
            "Professioneller Mallehrer",
            "Metallschreinerei",
            "Metallunterricht",
            "Metallurgie und Werkstofftechnik",
            "Meteorologische Technik",
            "Obstbau",
            "Herstellung plissierter westlicher Musikinstrumente",
            "Plissee-Volksmusikinstrumente herstellen",
            "Plissee-Kunstmusikinstrumente herstellen",
            "Technisches Zeichnen von Architekturgebäuden",
            "Die Architektur",
            "Möbelskelett und Polsterung",
            "Möbeldekoration Kunst",
            "Möbel- und Innenanstrich",
            "Möbel- und Dekorationsunterricht",
            "Modekleidungsdesign",
            "Mode-Design",
            "Modedesign-Ausbildung",
            "Mode- und Textildesign",
            "Mode- und Textildesign",
            "Moderner Tanz",
            "Molekularbiologie und Genetik",
            "Molekularbiologie, Genetik und Bioingenieurwesen",
            "Buchhaltung",
            "Buchhaltungsinformationssysteme",
            "Die Konten prüfen",
            "Buchhaltung und Finanzmanagement",
            "Buchhaltungs- und Finanzunterricht",
            "Küche",
            "Kochkunst und Management",
            "Kundenvertretung",
            "Übersetzen und Dolmetschen (Deutsch)",
            "Übersetzung und Dolmetschen (Arabisch)",
            "Übersetzen und Dolmetschen (Bulgarisch)",
            "Übersetzung und Dolmetschen (zweisprachig: Englisch-Deutsch)",
            "Übersetzung und Dolmetschen (zweisprachig: Englisch-Französisch)",
            "Übersetzen und Dolmetschen (Chinesisch)",
            "Übersetzen und Dolmetschen (Persisch)",
            "Übersetzen und Dolmetschen (Französisch)",
            "Übersetzen und Dolmetschen (Französisch)",
            "Übersetzung und Dolmetschen (Englisch)",
            "Übersetzen und Dolmetschen (Russisch)",
            "Übersetzen und Dolmetschen (Türkisch-Deutsch-Englisch)",
            "Übersetzen und Dolmetschen (Türkisch-Englisch-Französisch)",
            "Musik",
            "Musikwissenschaften",
            "Musikalische Bildung",
            "Musiktechnologie",
            "Musiktheorie",
            "Musikgemeinschaften",
            "Musikwissenschaft",
            "Stickunterricht",
            "Blasinstrumente und Schlaginstrumente",
            "Kernenergietechnik",
            "Oboe",
            "Audiologie",
            "Offsetdruck",
            "Vorschulunterricht",
            "Oper",
            "Operngesang",
            "Opern- und Konzertgesang",
            "Betrieb",
            "Optische und akustische Technik",
            "Management des ökologischen Landbaus",
            "Verantwortliche Organisation",
            "Forsttechnik",
            "Forsttechnik",
            "Orthetik-Prothetik",
            "Orthopädische Prothetik und Orthetik-Techniker",
            "Osmanische Vergleichende Musik",
            "Hotel Management",
            "Autolack",
            "Elektromechanik für Kraftfahrzeuge",
            "Karosserie",
            "Fahrzeugtechnik",
            "Automobilunterricht",
            "Schauspielkunst",
            "Vorderbüro",
            "Besondere Bildung",
            "Sonderschullehrerin",
            "Gebäck",
            "Marketing",
            "Marketinglehrer",
            "Performance",
            "Perfusion",
            "Erdöl- und Erdgastechnik",
            "Erdöl Petrochemie",
            "Benzin Raffinerie",
            "Landschaft",
            "Landschaftsarchitektur",
            "Pilotenausbildung",
            "Lotsen",
            "Klavier",
            "Klavierreparatur",
            "Klavier-Harfen-Gitarre",
            "Kunststoffverarbeitung",
            "Kunststoffform",
            "Plastische Kunst",
            "Plastische Kunst",
            "Plastische Kunst und Malerei",
            "Polymertechnik",
            "Polnische Sprache und Kultur (Polnisch)",
            "Popmusik singen",
            "Vorgeschichte",
            "Prozess",
            "Protohistorie und Kleinasien-Archäologie",
            "Psychologie",
            "Radio und Fernsehen",
            "Radio, Fernsehen und Kino",
            "Radiologietechniker",
            "Radio Fernsehprogramm",
            "Elektrische Schienensysteme Elektronisch",
            "Schienensystembau",
            "Betrieb von Schienensystemen",
            "Schienensystemmaschine",
            "Mechatronik für Schienensysteme",
            "Schienensystemtechnik",
            "Anleitung und psychologische Beratung",
            "Werbedesign und Kommunikation",
            "Werbung",
            "Erholung",
            "Erholungsmanagement",
            "Bild",
            "Malerei-Druckkunst",
            "Kunstunterricht",
            "Kunstunterricht",
            "Restaurierung",
            "Reservierung",
            "Russische Sprache und Literatur",
            "Windenergieanlagen",
            "Haarpflege",
            "Gesundheitserziehung",
            "Gesundheitsverwaltung",
            "Management von Gesundheitseinrichtungen",
            "Management von Gesundheitseinrichtungen",
            "Management von Gesundheitseinrichtungen",
            "Gesundheitsbeauftragter",
            "Gesundheits-Management",
            "Bühnendekore und Kostüme",
            "Darstellende Künste",
            "Bühnenbild",
            "Bühnen- und Performing Arts Management",
            "Kunst (Design) Management",
            "Erhaltung und Restaurierung von Kunstwerken",
            "Kunstgeschichte",
            "Kunstdesign",
            "Kunst- und Kulturmanagement",
            "Kunst und Design",
            "Kunstmanagement",
            "Industrielle Stickerei",
            "Sattlerproduktion",
            "Sattlermodellierung",
            "Verkaufspersonal",
            "Seitensekretariat",
            "Gemüse- und Obstverarbeitung",
            "Gemüseanbau",
            "Keramik",
            "Keramikunterricht",
            "Keramische Kunst",
            "Keramik und Glas",
            "Keramik- und Glasdesign",
            "Freie Keramikformung",
            "Siebdruck und Tampondruck",
            "Kapitalmarkt- und Portfoliomanagement",
            "Kapitalmarkt",
            "Kapitalmarktprüfung und -rating",
            "Bedienung",
            "Sprachtraining",
            "Reisemanagement",
            "Reisemanagement und Tourismusberatung",
            "Reisemanagement- und Tourismusberatungstraining",
            "Ausbildung in Reisemanagement und Tourismusberatung",
            "Unterricht im Klassenzimmer",
            "Überglasurdekoration",
            "Versicherung",
            "Versicherung",
            "Versicherungs- und Risikomanagement",
            "Versicherung und soziale Sicherheit",
            "Kino und digitale Medien",
            "Kino und Fernsehen",
            "Sinologie",
            "System Entwicklung",
            "Ziviles Lufttransportmanagement",
            "Zivilluftfahrtmanagement",
            "Politikwissenschaft",
            "Politikwissenschaft und öffentliche Verwaltung",
            "Politikwissenschaft und internationale Beziehungen",
            "Kühlsysteme",
            "Soziale Unterstützungsdienste",
            "Sozialanthropologie",
            "Lehrer für Sozialkunde",
            "Geisteswissenschaften",
            "Soziale Dienste",
            "Soziologie",
            "Sportwissenschaften",
            "Sport Management",
            "Statische Konstruktion Technischer Entwurf",
            "Fischereiproduktion",
            "Wasserwissenschaften und Ingenieurwesen",
            "Meeresfrüchte",
            "Fischereiingenieurwesen",
            "Der Sümeroloj",
            "Zierpflanzen und Landschaft",
            "Milchverarbeitung",
            "Molkereitechnik",
            "Singen",
            "Stadt- und Regionalplanung",
            "Schmuckherstellung",
            "Schmuckdesign",
            "Schmucktechnologie und Design",
            "Bearbeitung der Produktionslehre",
            "Grundbuch Kataster",
            "Anbetung",
            "Landwirtschaftliche Werkzeuge und Maschinen",
            "Agrarlabor",
            "Landwirtschaftliche Wirtschaft",
            "Landwirtschaftliche Maschinen",
            "Agrartechnologie",
            "Agrarbiotechnologie",
            "Agrargenetik",
            "Landwirtschaftliche Strukturen und Bewässerung",
            "Geschichte",
            "Geschichtsunterricht",
            "Prähistorische Archäologie",
            "Anbau von Feldfrüchten",
            "landwirtschaftliche Pflanzen",
            "Design- und Konstruktionsunterricht",
            "Schutz und Reparatur des tragbaren Kulturerbes",
            "Boots- und Yachtbau",
            "Technische Produktion Veröffentlichung",
            "Technologie- und Informationsmanagement",
            "Textil",
            "Textildruck und -musterung",
            "Textilveredelungsprozesse (Veredelung)",
            "Textilfärbung",
            "Textillabor",
            "Textilweberei und Strickausbildung",
            "Textilentwicklung und Marketing",
            "Textiltechnik",
            "Textilunterricht",
            "Textildesign",
            "Textildesign und -produktion",
            "Lehrer für Textilveredelung",
            "Textil- und Ledermodedesign",
            "Textil- und Modedesign",
            "Telekommunikationstechnik",
            "Telekommunikationsausbildung",
            "Fernsehjournalismus und Programmierung",
            "Grundlagenwissenschaften",
            "Theorie",
            "Installationslehrer",
            "Erleuchtung",
            "Medizinische Bildgebungssysteme",
            "Medizinische Labor- und Nicht-Patienten-Applikationsgeräte",
            "Medizinischer Labortechniker",
            "Medizinisches Sekretariat",
            "Medizin",
            "Medizintechnik",
            "Handelssekretariat",
            "Tiefdruck",
            "Theater",
            "Theaterkritik und Dramaturgie",
            "Sozial- und Politikwissenschaften",
            "Boden",
            "Bodenkunde und Pflanzenernährung",
            "Formgebung auf Drehmaschine",
            "Posaune",
            "Trompete",
            "Tuba",
            "Tourismusanimation",
            "Tourismus Verwaltung",
            "Tourismusmanagement und Hotelmanagement",
            "Tourismusberatung",
            "Tourismus- und Hotelmanagement",
            "Tourismus und Gastronomie",
            "Verbraucherdienste",
            "Türkische Sprache und Literatur",
            "Türkischer Sprach- und Literaturunterricht",
            "Türkische religiöse Musik",
            "Türkische Volksmusik",
            "Türkisches Volksmusikinstrumententraining",
            "Türkisches Volksmusik-Sprachtraining",
            "Türkische Volkstänze",
            "Türkische Folklore",
            "Türkische Musik",
            "Türkische Musikgrundwissenschaften",
            "Türkische Musik",
            "Türkische Kunstmusik",
            "Türkisches Kunstmusik-Sprachtraining",
            "Türkische Kunstmusik-Grundwissenschaften",
            "Türkisch - Mathematik",
            "Türkischlehrer",
            "Türkische Lehrerausbildung",
            "Tabakfachschule",
            "Fernsehreporter",
            "Flugzeugelektronik",
            "Flugzeugkörper Motor",
            "Flugzeuge elektrisch-elektronisch",
            "Flugzeugkarosserie-Motor",
            "Wartung der Flugzeugkarosserie",
            "Flugzeugtechnik",
            "Verkehrstechnik",
            "Transport und Logistik",
            "Internationale Studien",
            "Internationale Finanzen",
            "Internationale Finanzen und Bankwesen",
            "Internationales Unternehmertum",
            "Internationale Theologie",
            "Internationale Beziehungen",
            "Internationale Beziehungen und die Europäische Union",
            "Internationale Beziehungen und maritime Sicherheit",
            "Internationale Geschäftsleitung",
            "Internationale Geschäfte",
            "Internationale Logistik",
            "Internationale Logistik und Transport",
            "Internationales Logistikmanagement",
            "Internationaler Handel",
            "Internationaler Handel und Finanzen",
            "Internationaler Handel und Finanzen",
            "Internationaler Handel und Management",
            "Internationaler Handel und Logistik",
            "Internationales Handels- und Logistikmanagement",
            "Internationaler Handel und Marketing",
            "Internationaler Handel, Logistik und Management",
            "Urdu Sprache und Literatur",
            "Weltraumwissenschaften und -technologien",
            "Raumfahrttechnik",
            "Blas- und Schlaginstrumente",
            "Produktionssystemtechnik",
            "Begabte Lehre",
            "Datenbankprogrammierung",
            "Veterinärgesundheit",
            "Tiermedizin",
            "Viola",
            "Cello",
            "Schlaginstrumente",
            "Körperpflege",
            "Web Programmierung",
            "Wildtierökologie und -management",
            "Gebäudeinnendekoration",
            "Gebäudeinstallationssysteme",
            "Gebäudeisolierung",
            "Oberflächenbeschichtung von Gebäuden",
            "Bauunterricht",
            "Aufbau einer Zeichnungsausbildung",
            "Building Design Education",
            "Lebenserhaltungs- und Behandlungsgeräte",
            "Altenpflege",
            "Yachtkapitän",
            "Gemeinsamer Religionsunterricht und gemeinsame Praktiken",
            "Saiteninstrumentenbau",
            "Streichinstrumente",
            "Streichinstrumente herstellen",
            "Schriftlicher Pressereporter",
            "Softwareentwicklung",
            "Neue Medien",
            "Neue Medien und Journalismus",
            "Lebensmittel- und Getränkemanagement",
            "Exekutivsekretariat",
            "Managementwissenschaften",
            "Managementwissenschaften (Fakultät für Wirtschaftswissenschaften)",
            "Management Sciences Programme",
            "Managementinformationssysteme",
            "Griechische Sprache und Literatur",
            "Hochspannungssysteme",
            "Sachbearbeiter",
            "Zaza Sprache und Literatur",
            "Der Zeotekn",
            "Olivenverarbeitung",
            "Unterrichten von geistig Behinderten",
            "Agrartechnik",
            "Zoologie, Tierwissenschaft"
    };
}
