package com.example.cv_translater;

public class HobiArrrayi {
    public String hobiarray[] = {
        "hobi secilmedi",
        "3d Drucken",
        "Draussen",
        "Krafttraining",
        "Gewichtheben",
        "Holzschnitzen",
        "Airsoft",
        "Akrobatik",
        "Action Figur",
        "Fischzucht",
        "Aquarium Landschaft",
        "Einkaufen",
        "Goldminenerkundung",
        "Amateurastronomie",
        "Fußball",
        "Cheerleader",
        "Animation",
        "Antiquität",
        "Autorennen",
        "Fahrzeugrestaurierung",
        "Fahrzeugbefestigung & Konstruktion",
        "Bienenzucht",
        "Eiskunstlauf",
        "Astronomie",
        "Ein Pferd reiten",
        "Schießen",
        "Schießsport",
        "Jagd",
        "Australischer Fußball",
        "Axt werfen",
        "Schuh",
        "Schuster",
        "Badminton",
        "Gartenbau",
        "Angeln",
        "Band",
        "Basketball spielen",
        "Tambourstab wirbeln",
        "Flag Football",
        "Baseball spielen",
        "Messerwurf",
        "Messersammlung",
        "Ein Messer machen",
        "Billard",
        "Tickets sammeln",
        "Computerprogrammierung",
        "Gebäude",
        "Reiten",
        "Beispiel der Vereinten Nationen",
        "Radfahren",
        "Einen Blog schreiben",
        "BMX",
        "Boxen",
        "Bonsai",
        "Bowling",
        "Gemälde",
        "Münzen sammeln",
        "Insektensammlung",
        "Breakdance",
        "Brasilianischer Jiujitsusu",
        "Topiary",
        "Rätsel",
        "Eishockey",
        "Schlittschuhlaufen",
        "Glasbläserei",
        "Kartophilie (Kartensammeln)",
        "Wäschemachen",
        "Cosplaying",
        "Couponing",
        "häkeln",
        "Kreuzworträtsel",
        "Teebeutel-Sammlung",
        "ziehen",
        "Blumen arrangement",
        "Blumensammlung und Presse",
        "Blumenzucht",
        "Feldhockey",
        "Chinesischer Domino",
        "Comic-Sammlung",
        "Zeichnung",
        "Keramik",
        "Mountainbike",
        "Bergsteigen",
        "Tanzen",
        "Spitze machen",
        "Darts",
        "Deltiologie (Postkartensammlung)",
        "Schmiede",
        "Experimentieren",
        "Marine Glass Collection",
        "Lederarbeiten",
        "Druckgussspielzeug",
        "Digitale Kunst",
        "Naht",
        "Disc Golf",
        "Distro Hopping",
        "Djing",
        "Wandern",
        "Weberei",
        "Kuscheltiersammlung",
        "Kampfkunst",
        "Theater",
        "Graffiti",
        "Verknoten",
        "Ephemera-Sammlung",
        "Brot machen",
        "Elektronisch",
        "Rekrutierung",
        "Alte Traditionen",
        "Skizzieren",
        "Fechten",
        "Esport",
        "Heimwerker",
        "Hausgemachtes Getränk",
        "Fantasy-Sport",
        "Backen",
        "Philatelie",
        "Filme anschauen",
        "Fußsack",
        "Fossile Jagd",
        "Fossicking",
        "Fotografie",
        "Fusilately (TELEFON-Sammlung)",
        "Football spielen",
        "Videospiel entwickeln",
        "Geocaching",
        "Gehen",
        "Golf",
        "Gongoozling",
        "Grafikdesign",
        "Büchsenmacher",
        "Sonneneinstrahlung",
        "Protokollierung",
        "Ringen",
        "Beim Schönheitswettbewerb",
        "hacken",
        "Luftsport",
        "Geisterjagd",
        "Tierphantasie",
        "Handball",
        "Kräuterkunde",
        "Herp Retention",
        "Herping",
        "Herping",
        "Eisschnelllauf",
        "Hobby Horsing",
        "Hula Pertussis",
        "Getränk mischen",
        "Innerhalb",
        "Skandinavisches Skaten",
        "Origami",
        "Japanischer Sport",
        "Gymnastik",
        "Jonglieren",
        "Judo",
        "der Jukske",
        "Kabaddi",
        "Kabarett",
        "Papierschnitzen",
        "Kaffeeröster",
        "Kalligraphie",
        "Camping",
        "Segeltuch",
        "Kanu",
        "Kanusport",
        "Karaoke",
        "Karate",
        "Kartenspiele",
        "Kart Race",
        "Rock Balancing",
        "Felsklettern",
        "Skifahren",
        "Skateboarding",
        "Schmetterlingsbeobachtung",
        "Kendama",
        "Urban Discovery",
        "Entdeckung",
        "Kurzwellen hören",
        "Schloss brechen",
        "Buchrestaurierung",
        "Buchdiskussionsclubs",
        "Büchersammlung",
        "Klassische Autos",
        "Brauen von Kombucha",
        "Kompost",
        "Joggen",
        "Hundesport",
        "Kricket",
        "Kryptographie",
        "Sandkunst",
        "Brettsport",
        "Vögel beobachten",
        "Vögel beobachten",
        "Rudern oder Rudern",
        "Flipper",
        "Larping",
        "Laseretikett",
        "Lego-Gebäude",
        "Briefkasten",
        "Longboarding",
        "Lotologie (Lottoscheinsammlung)",
        "Bergwerk",
        "Höhlenforschung",
        "Makramee",
        "Bilden",
        "Pilzsuche / Mykologie",
        "Tischtennis",
        "Meditation",
        "Metall Verarbeitung",
        "Metalldetektion",
        "Meteorologie",
        "Magnetfischen",
        "Untersuchung mit einem Mikroskop",
        "Mineraliensammlung",
        "Möbelgebäude",
        "Mode",
        "Mode-Design",
        "Modellbau",
        "Modellflugzeuge",
        "Modellbau",
        "Motorsport",
        "Kerzenherstellung",
        "Musik hören",
        "Musikinstrumente spielen",
        "Stickerei",
        "Netzball",
        "Ultimativer Frisbee",
        "Bogenschießen",
        "Lesen",
        "Orientierungslauf",
        "Automatische Audiophilie",
        "Handarbeit",
        "Spielzeug",
        "Puppen",
        "Schauspielkunst",
        "Lernen",
        "Stricken",
        "Paintball",
        "Fallschirmsprung",
        "Parfüm",
        "Eislaufrennen",
        "Käse machen",
        "Phillumeny",
        "Beach-Volleyball",
        "Podcast-Hosting",
        "Podcasts anhören",
        "Pou",
        "Poker",
        "Polo",
        "Powerlifting",
        "Streiche",
        "Briefmarkensammlung",
        "Puzzle sagen",
        "Radio Control Autorennen",
        "Rafting",
        "Rugby",
        "Racquetball",
        "Abseilen",
        "klopfen",
        "Modellierung des Schienenverkehrs",
        "Nacharbeiten",
        "Wettbewerbsfähige Hobbys",
        "Farbschutz",
        "Roboterkampf",
        "Zauberwürfel",
        "Rugby League Fußball",
        "Kunstsammlung",
        "Schach",
        "Scrapbooking",
        "Scutelliphily",
        "Muschelsammlung",
        "Gemüseanbau",
        "Freestyle Fußball",
        "Ausstellungsübung",
        "Audio-Geräte-Enthusiast",
        "Reise",
        "Shogi",
        "Komprimiertes Blumenhandwerk",
        "Prüfungen",
        "Sammlung von Kino- und Filmandenken",
        "Skimboarden",
        "Slacklining",
        "Snowboard",
        "Seifenherstellung",
        "Weicher Ball",
        "Sozialen Medien",
        "Surfen",
        "Speedcubing",
        "Sportmauerwerk",
        "Standup-Comedy",
        "Wassersport",
        "Hydroponik",
        "Wasserball",
        "Fahrt",
        "Wein machen",
        "Singen",
        "Genealogie",
        "Süßwaren",
        "vermodern",
        "Präparatoren",
        "Tai Chi",
        "Schmuckherstellung",
        "Bearbeitung",
        "Diskussion",
        "Steinsprung",
        "Steinsammlung",
        "Roller Skates",
        "Rollschuhlaufen",
        "Taekwondo",
        "Fernsehen",
        "Grundsprung",
        "Tennis",
        "Tennis Polo",
        "Sparsamkeit",
        "Steigen",
        "Nagel Kunst",
        "Versammlung",
        "Trainspotting",
        "Triathlon",
        "Tour Skaten",
        "Plattensammlung",
        "Gerätetauchen",
        "Flugzeug-Spotting",
        "Fliegende Scheibe",
        "Einen Drachen fliegen lassen",
        "Gepäckwagen",
        "Satelliten schauen",
        "Videobearbeitung",
        "Videospielsammlung",
        "Videospiel",
        "Videophil",
        "Wikipedia bearbeiten",
        "Schallplatten",
        "Vintage-Kleidung",
        "Volleyball",
        "Bodybuilding",
        "Worldbuilding",
        "Fremdsprachen lernen",
        "Kreatives Schreiben",
        "Segeln",
        "Koch",
        "Yoga",
        "Rennrad",
        "du schnitzst",
        "Quilten",
        "Yo-Yoing",
        "Slot Car Racing",
        "Hochleistungsrakete",
        "Gehen",
        "Wandern / Rucksackwandern",
        "Schwimmen",
        "Lebkuchen hausgemacht",
    };
}
