package com.example.cv_translater;

public class Isarrayi {

    public String[] pozisyon = {
            "Meslek Secilmedi"    ,
            "Arbeitsschutzspezialist der Klasse A.",
            "EU-Projektassistent",
            "EU-Projektentwicklungsspezialist",
            "Vertreter der Agentur",
            "Rettungsschwester",
            "Rettungssanitäter",
            "Notfallmediziner",
            "Facharzt für Forensische Medizin",
            "Aerodynamischer Ingenieur",
            "Netzwerkentwicklungsmanager",
            "Netzwerkinstallationsingenieur",
            "Netzwerkarchitekt",
            "Support-Ingenieur für Netzwerksysteme",
            "Spezialist für Netzwerk- und Cybersicherheit",
            "Netzwerkadministrator",
            "Holzbearbeitungsingenieur",
            "Holzingenieur",
            "Holzbearbeitungstechniker",
            "Schwerfahrzeugfahrer",
            "Holzschreiner",
            "Holzmeister",
            "Familienberater",
            "Familiendoktor",
            "Akademisches Personal",
            "Akademiemitglied",
            "Zubehör Designer",
            "Aktiver Verkaufsberater",
            "Aktiver Verkäufer",
            "Aktiver Vertriebsmitarbeiter",
            "Aktivierungselement",
            "Aktivitätsmanager",
            "Aktuar",
            "Akustischer Experte",
            "Receivable Tracking Staff",
            "Kellner à la carte",
            "Oberst",
            "Algorithmusentwicklungsingenieur",
            "Deutschlehrer",
            "Spezialist für alternative Kanalentwicklung",
            "Infrastrukturingenieur",
            "Aluminium Tischlermeister",
            "Aluminium Handlauf Master",
            "Krankenwagenarzt",
            "Krankenwagenfahrer",
            "Operationsschwester",
            "OP-Personal",
            "Analytiker",
            "Analytischer CRM-Spezialist",
            "Analytischer CRM Manager",
            "Spezialist für die Entwicklung analytischer Methoden",
            "Spezialist für die Validierung analytischer Methoden",
            "Analysetechniker",
            "Analytiker",
            "Analyse- und Berichtsspezialist",
            "Kindergartenleiter",
            "Kindergärtnerin",
            "Anatomielehrer",
            "Android-Entwickler",
            "Anästhesist",
            "Anästhesie-Krankenschwester",
            "Anästhesietechniker",
            "Anästhesietechniker",
            "Anästhesist",
            "Animationskünstler",
            "Animator",
            "Angio Krankenschwester",
            "Angio-Techniker",
            "Trainer",
            "Lagerhausmanager",
            "Fahrzeuginspektionstechniker",
            "Spezialist für Fahrzeuginspektion",
            "Analyst für Suchmaschinenoptimierung (SEO)",
            "Berater für Suchmaschinenoptimierung (SEO)",
            "Spezialist für Suchmaschinenoptimierung (SEO)",
            "Spezialist für Suchmaschinenmarketing (SEM)",
            "Arrangeur",
            "Arabischlehrer",
            "Arabischer Übersetzer",
            "Forschungsentwicklung / F & E-Manager",
            "Forschungsentwicklung / F & E-Ingenieur",
            "Forschungsentwicklung / F & E-Projektingenieur",
            "Forschungsentwicklung / F & E Projektmanager",
            "Forschungsentwicklung / F & E verantwortlich",
            "Forschungsentwicklung / F & E-Spezialist",
            "Forscher",
            "Spezialist für Schnittstellensoftware",
            "F & E-Ingenieur",
            "F & E- und Qualitätsspezialist",
            "Archäologe",
            "Rigger",
            "Reeder",
            "Archivoffizier",
            "Archivverantwortlich",
            "Archivspezialist",
            "Archivmanager",
            "Aufzugsmeister",
            "Betreiber einer Asphaltanlage",
            "Assistent",
            "Asp.net Software Engineer",
            "rotzig",
            "Astronomielehrer",
            "Unteroffizier",
            "Koch",
            "Koch",
            "Avionik-Ingenieur",
            "Avionik-Techniker",
            "Projektspezialist der Europäischen Union",
            "Anwalt",
            "Rechtsanwalt",
            "Schuhdesigner",
            "Lichtdesigner",
            "",
            "Arbeitsschutzspezialist der Klasse B.",
            "Backoffice Manager",
            "Baglama Lehrer",
            "Gärtner",
            "Wartungsmanager",
            "Wartungsarbeiter",
            "Wartungs- und Reparaturingenieur",
            "Wartungsreparaturtechniker",
            "Wartungstechniker",
            "Ballettlehrer",
            "Bank-Manager",
            "Bankinspektor",
            "Bank Mitarbeiter",
            "Bankfilialleiter",
            "Beauftragter für Bankgeschäfte",
            "Bankettmanager",
            "Bankettverkäufer",
            "Bankangestellter",
            "Barboy",
            "Barista",
            "Barista Trainer",
            "Barkeeper / Bardame",
            "Presseberater",
            "Pressereferent",
            "Presse- und PR-Manager",
            "Presse- und PR-Spezialist",
            "Basketball Trainer",
            "Chefarchitekt",
            "der Başçarkç",
            "Allgemeiner Chirurg",
            "Oberschwester",
            "Erster Sekretär",
            "Superintendent",
            "Chefinspektor",
            "Baby Krankenschwester",
            "Sportlehrer",
            "Bewachen",
            "Bürgermeister",
            "Zertifizierungsspezialist",
            "Ernährungsberater",
            "Betreiber einer Betonanlage",
            "Techniker für weiße Ware",
            "Gehirnchirurg",
            "Ticketverkaufsvertreter",
            "Informationssicherheits-Manager",
            "Informationssicherheitsbeauftragter",
            "Spezialist für Informationssicherheit",
            "IT-Support-Mitarbeiter",
            "IT Personal",
            "IT-Koordinator",
            "IT-Manager",
            "IT-Ingenieur",
            "IT-Betreiber",
            "Verantwortlich für die Informationsverarbeitung",
            "IT-Techniker",
            "Computerexperte",
            "Manager für Informationssysteme",
            "Spezialist für Informationssysteme",
            "Manager / Direktor für Informationssysteme",
            "Berater für Informationstechnologien",
            "Verantwortlicher Support für Informationstechnologien",
            "Direktor für Informationstechnologien",
            "Manager für Informationstechnologien",
            "Ingenieur für Informationstechnologien",
            "Computerlehrer",
            "Computer-Operator",
            "Computertechniker",
            "Computer-Operator",
            "Computer Lehrer",
            "Computerprogrammierer",
            "Computertechniker",
            "Computertechniker",
            "Experte",
            "Spezialist für IT-Verbrechen",
            "IKT-Lehrer",
            "IT-Experte",
            "Haupt",
            "Privater Rentenberater",
            "Privater Rentenspezialist",
            "Individueller Kundenvertreter",
            "Individueller Portfoliomanager / Director",
            "Einzelner Vertriebsmitarbeiter",
            "Biochemietechniker",
            "Biochemie-Spezialist",
            "Biochemiker",
            "Biologe",
            "Biologieingenieur",
            "Biologie Lehrer",
            "Techniker für biomedizinische Geräte",
            "Biomedizintechniker",
            "Biomedizinischer Techniker",
            "Biomedizinischer Techniker",
            "Biomedizinischer Spezialist",
            "Biyoteknolog",
            "Biotechnologiespezialist",
            "Blog Writer",
            "Spulenmeister",
            "Boxtrainer",
            "Spezialist für Gehaltsabrechnung",
            "Manager für Gehaltsabrechnung und Personalangelegenheiten",
            "Spezialist für Gehaltsabrechnung und persönliche Angelegenheiten",
            "Exchange-Experte",
            "Borwerk Betreiber",
            "Lacktechniker",
            "Paint Shop Manager",
            "Regionaldirektor",
            "Regionaler Verkausmanager",
            "Regionaler Verkausmanager",
            "Regionaler Vertriebsmitarbeiter",
            "Regionaler Verkausmanager",
            "Konditormeister",
            "Makler",
            "Bulgarischer Lehrer",
            "Dieser Ort",
            "Eislauftrainer",
            "Büroangestellter",
            "Büropersonal",
            "Direktor für Budgetplanung",
            "Spezialist für Budgetplanung",
            "Budget-Spezialist",
            "Budget- und Finanzspezialist",
            "Budget- und Berichtsanalyst",
            "Spezialist für Budget und Berichterstattung",
            "Big Data Architect",
            "Big Data Engineer",
            "",
            "Arbeitsschutzspezialist der Klasse C.",
            "Rettungsschwimmer",
            "Spezialist für Girokonten",
            "Chirurgischer Assistent",
            "Chirurgische Krankenschwester",
            "Hautpflegespezialist",
            "CNC-Laserschneidoperator",
            "CNC Laser Operator",
            "CNC-Bediener",
            "CNC-Plasmaschneidoperator",
            "CNC-Techniker",
            "CNC-Maschinenbediener",
            "CNC-Drehmaschinenbediener",
            "Geografielehrer",
            "CRM Analyst",
            "CRM-Berater",
            "Call Center-Mitarbeiter",
            "Call Center Qualitätsspezialist",
            "Call Center Manager",
            "Call Center-Kundenvertreter",
            "Call-Center Angestellter",
            "Call Center Teamleiter",
            "Spezialist für Kiefer- und Gesichtschirurgie",
            "Umweltbeauftragter",
            "Umweltingenieur",
            "Umweltgesundheitstechniker",
            "Umwelttechniker",
            "Umweltspezialist",
            "Umweltingenieur",
            "Schokoladenmeister",
            "Illustrator / Illustrator",
            "Lehrer für Kinderentwicklung",
            "Spezialist für Kinderentwicklung",
            "Kinderpsychiater",
            "Spezialist für Kindergesundheit und Krankheiten",
            "",
            "Kindermädchen",
            "Facharzt für Innere Medizin",
            "Taucher",
            "Tauchlehrer",
            "Tanzlehrer",
            "Tanzlehrer",
            "Tänzer",
            "Detektiv",
            "Schatzmeister",
            "Bewertungsspezialist",
            "Dean",
            "Dekorateur",
            "Eisen Tischlerei Meister",
            "Wirtschaftsprüfer",
            "Assistant Auditor",
            "Prüfungsleiter",
            "Prüfungsspezialist",
            "Ingenieur für Seetransportmanagement",
            "Lagerhausmanager",
            "Lederingenieur",
            "Ledertechniker",
            "Dermatologe",
            "Dermokosmetischer Spezialist",
            "Musterdesigner",
            "Designer",
            "Unterstützungspersonal",
            "Support Services Manager",
            "DevOps-Ingenieur",
            "Außenhandelsberater",
            "Außenhandelsdirektor",
            "Außenhandelsbeauftragter",
            "Außenhandelschef",
            "Spezialist für Außenhandelsassistenten",
            "Außenhandelsspezialist",
            "Spezialist für digitale Transformation",
            "Manager für digitale Inhalte",
            "Spezialist für digitale Kommunikation",
            "Digital Brand Manager",
            "Spezialist für digitale Medien",
            "Digital Marketing Manager",
            "Verantwortliches digitales Marketing",
            "Digital Marketing Intern",
            "Spezialist für digitales Marketing",
            "Digital Marketing Manager",
            "Digitaler Projektmanager",
            "Verkaufsleiter für digitale Werbung",
            "Logopäde",
            "Schneidemaschinenbediener",
            "Lehrer für religiöse Kultur und Ethik",
            "Lenklehrer",
            "Direktor",
            "Discjockey / DJ",
            "Dispatcher",
            "Verteiler",
            "Zahnarzt",
            "Zahnarztassistent",
            "Zahnprothetiker",
            "Zahntechniker",
            "Zahntechniker",
            "Dialysetechniker",
            "Ernährungsberater",
            "Entwicklungsingenieur",
            "Dizayn Office Architect",
            "String-Operator",
            "Setzer",
            "Erdgastechniker",
            "Arzthelferin",
            "Weboperator",
            "Dokumentationsbeauftragter",
            "Hardware Ingenieur",
            "Hardware-Design-Ingenieur",
            "Eiscreme-Meister",
            "Gießereimanager",
            "Gießereibeamter",
            "Dönermeister",
            "Dramatrainer",
            "Schauspiellehrer",
            "Script Editor",
            "Entwässerungsingenieur",
            "Drohnenpilot",
            "Wallpaper Master",
            "",
            "Hebamme",
            "Marmorierender Kunstlehrer",
            "Apotheker",
            "Apothekertechniker",
            "Literaturlehrer",
            "Editor",
            "E-Learning-Manager",
            "Bildungsberater",
            "Trainingscoach",
            "Übungskoordinator",
            "Education Verkaufsberater",
            "Spezialist für Bildungsassistenten",
            "Bildungsspezialist",
            "Spezialist für Aus- und Weiterbildung",
            "Lehrer",
            "EKG-Techniker",
            "Ökologen",
            "Ökonomen",
            "Ökonom",
            "Baggerfahrer",
            "Experte",
            "Extrusionspresse Bediener",
            "Handwerkslehrer",
            "Elektrisches Wartungspersonal",
            "Ingenieur für elektrische Wartung",
            "Elektrischer Wartungstechniker",
            "Ingenieur für Elektrotechnik",
            "Techniker für Elektroelektronik",
            "Elektrischer elektronischer Techniker",
            "Ingenieur für Elektrotechnik",
            "Elektrische Formeni",
            "Elektroingenieur",
            "Elektrolehrer",
            "Elektroprojektingenieur",
            "Elektrischer Bauleiter",
            "Elektrotechniker",
            "Elektriker",
            "Elektroingenieur",
            "Elektroniker",
            "Elektronischer Konstrukteur",
            "Elektroniker",
            "Elektroniker",
            "Elektronik- und Kommunikationsingenieur",
            "Elektroniker",
            "Elektroneurophysiologietechniker",
            "Embryologe",
            "Immobilienberater",
            "Index Reading Officer",
            "Spezialist für Endokrinologie",
            "Endoskopie-Krankenschwester",
            "Wirtschaftsingenieur",
            "Industrieller Automatisierungstechniker",
            "Arbeitspsychologe",
            "Ingenieur für Industriedesign",
            "Industriedesigner",
            "Energieingenieur",
            "Energiesystemingenieur",
            "Energiehandelsspezialist",
            "Energieassistent",
            "Energieexperte",
            "Energiemanager",
            "Infektionsspezialist",
            "Epidemiologie-Arzt",
            "Ergotherapeut",
            "ERP-Berater",
            "ERP-Ingenieur",
            "ERP-Projektmanager",
            "ERP verantwortlich",
            "ERP-Spezialist",
            "E-Sportler",
            "Kosmetikerin",
            "E-Commerce-Berater",
            "E-Commerce-Direktor",
            "E-Commerce-Kategoriemanager",
            "E-Commerce-Manager",
            "E-Commerce-Berichtsspezialist",
            "E-Commerce verantwortlich",
            "E-Commerce-Spezialist",
            "E-Commerce-Manager",
            "Event-Koordinator",
            "Veranstaltungsspezialist",
            "Event und Organisation verantwortlich",
            "Event Manager",
            "Studienlehrer",
            "Häusliche Krankenschwester",
            "",
            "",
            "Fabrikleiter",
            "Pharmakovigilanz-Beauftragter",
            "Persischer Lehrer",
            "Vertragsverfolgung",
            "Verantwortlicher Subunternehmer",
            "Fertiger",
            "Philosophy Group Lehrer",
            "Philosophielehrer",
            "Naturwissenschafts-Lehrer",
            "Wissenschaftsmanager",
            "Lehrer für Wissenschaft und Technologie",
            "Schmiedeeisen Meister",
            "Extra",
            "Finanzberater",
            "Finanzdirektor",
            "Stellvertretender Generaldirektor für Finanzen",
            "Finanzkoordinator",
            "Finanzmanager",
            "Finanzbeamter",
            "Finanzexperte",
            "Finanzmanager / Direktor",
            "Finanzanalyst",
            "Finanzberater",
            "Finanzversicherungsberater",
            "Finanzkontrolleur",
            "Spezialist für Finanzplanung",
            "Spezialist für Finanzberichterstattung",
            "Finanzmanager",
            "Fitnesstrainer",
            "Phytopathologietechniker",
            "Preisanalyst",
            "Preisspezialist",
            "Preis- und Kampagnenspezialist",
            "Preis- und Kampagnenmanager",
            "Machbarkeitsspezialist",
            "Physikingenieur",
            "Physik Lehrer",
            "Physiotherapeut",
            "Spezialist für Physiotherapie",
            "Spezialist für Physiotherapie und Rehabilitation",
            "Physiotherapeut",
            "Physiotherapeut",
            "Phlebotomie-Spezialist",
            "Fondsmanager",
            "Forex Experte",
            "Gabelstaplerfahrer",
            "Vorarbeiter",
            "Formulierungsspezialist",
            "Foto Editor",
            "Fotograf",
            "Französischlehrer",
            "Betrugsexperte",
            "Betrugsmanager",
            "Fräsbetreiber",
            "Faires Hostel",
            "Fussball Trainer",
            "",
            "Bedienung",
            "Facharzt für Gastroenterologie",
            "Immobilienmakler",
            "Immobiliengutachter",
            "Immobilienexperte",
            "Spezialist für Immobilienentwicklung",
            "Immobilienverkaufsberater",
            "Immobilien Anlageberater",
            "Journalist",
            "Nachtwächter",
            "Income Expert Assistant",
            "Einkommensspezialist",
            "Schiffbaumanager",
            "Schiffbauer",
            "Schiffskontrolloffizier",
            "Schiffsmechaniker",
            "Schiffsbetriebsoffizier",
            "Spezialist für Allgemeinchirurgie",
            "Generalkoordinator",
            "General Accounting Specialist",
            "stellvertretender Geschäftsführer",
            "Generalsekretär",
            "Chefredakteur",
            "Gentechniker",
            "Genetiker",
            "Geomatischer Ingenieur",
            "Geometrielehrer",
            "geotechnischer Ingenieur",
            "Gerontologe",
            "Spezialist für Lebensmittelextrusion",
            "Lebensmittelkontrolleur",
            "Lebensmitteltechniker",
            "Lebensmitteltechniker",
            "Lebensmitteltechniker",
            "Unternehmer",
            "Kassierer",
            "Mystery Kunde",
            "Spezialist für Brustkrankheiten",
            "Embedded System Engineer",
            "Embedded Software Engineer",
            "Visuelle Bearbeitung / Präsentation / Gestaltungselement",
            "Visuelle Bearbeitung / Präsentation / Design Officer",
            "Spezialist für visuelle Kommunikation",
            "Lehrer für Bildende Kunst",
            "Spezialist für visuelles Design",
            "Kameramann",
            "Spezialist für Augenkrankheiten",
            "Aufsichtspersonal",
            "Spezialist für Grafikdesign",
            "Grafikdesigner",
            "Grafiker",
            "Grader Operator",
            "GSM-Techniker",
            "Ingenieur für Antriebsstrangsysteme",
            "Ingenieur für Energiesysteme",
            "Zollbeamter",
            "Zollbeamter",
            "Zollberater",
            "Sicherheitskoch",
            "Sicherheitsbeamter",
            "Sicherheitsmanager",
            "Sicherheitschef",
            "Schönheitsexperte",
            "",
            "Nachrichtenreporter",
            "Newsreader",
            "HACCP-Spezialist",
            "HACCP Manager",
            "Schiedsrichter",
            "Richter",
            "Teppich Exsikkator",
            "Volkstanzlehrer",
            "Comminity Relationship Manager",
            "Pressesprecher",
            "PR-Spezialist",
            "PR-Manager / Direktor",
            "Rohstoffeinkaufsspezialist",
            "Rohstoffingenieur",
            "Operations Officer",
            "Topographischer Ingenieur",
            "Kartentechniker",
            "Kartentechniker",
            "Vermessungs- und Katasteringenieur",
            "Karteningenieur",
            "Schadensberater",
            "Anspruchsspezialist",
            "Krankenschwester",
            "Patientenberater",
            "Patient Services Manager",
            "Manager für Patientenbeziehungen",
            "Patient Relations Officer",
            "Krankenhausmanager",
            "Linienbetreiber",
            "Penman",
            "Tiersitter",
            "Finanzspezialist",
            "Hubschrauber Pilot",
            "Hämatologie-Spezialist",
            "Krankenschwester",
            "Konto-Spezialist",
            "Hydrogeologie-Ingenieur",
            "Wasserbauingenieur",
            "Hydrotherapeuten",
            "Hethitologe",
            "Homologationsingenieur",
            "Husch",
            "Hostess",
            "Rechtsberater",
            "Rechtsberater",
            "Rechtssekretär",
            "Pflegeheimkrankenschwester",
            "HLK-Ingenieur",
            "",
            "Lichttechniker",
            "",
            "Ausführender Anwalt",
            "Geschäftsführer",
            "Geschäftsführer",
            "Executive Tracking Staff",
            "Interne Rechnungsprüfer",
            "Interner Audit Manager",
            "Assistent der Internen Revision",
            "Interner Revisionsspezialist",
            "Interner Audit Manager",
            "Spezialist für innere Krankheiten",
            "Innenarchitekt",
            "Content-Editor",
            "Spezialist für Inhaltsplanung",
            "Content Manager",
            "Verwaltungsmanager",
            "Verwaltungspersonal",
            "Verantwortlich für administrative Angelegenheiten",
            "Spezialist für Verwaltungsangelegenheiten",
            "Verwaltungsmanager",
            "Manager / Direktor für Verwaltungsangelegenheiten",
            "Verwaltungs- und Finanzmanager",
            "Ausschreibungsberater",
            "Exportpersonal",
            "Exportmanager",
            "Export Operation Specialist",
            "Exportspezialist",
            "Kühltechniker für Klimaanlagen",
            "Wirtschaftslehrer",
            "Trainer für fortgeschrittene Fahrtechniken",
            "Kommunikationsspezialist",
            "Erste-Hilfe-Trainer",
            "Erste-Hilfe-Lehrer",
            "Fertigungsleiter",
            "Fertigungsingenieur",
            "Verantwortlich für die Herstellung",
            "Hinrichtungs- und Schutzbeauftragter",
            "Englisch Lehrer",
            "Englischlehrer",
            "Innovationsspezialist",
            "Assistent des Personalmanagements",
            "Personalberater",
            "Senior Manager der Personalabteilung",
            "Personalschulungsspezialist",
            "Personal",
            "Human Resources Assistant General Manager",
            "Personalchef",
            "Assistent der Personalabteilung",
            "Leiter der Personalabteilung",
            "Human Resources Intern",
            "Personalchef",
            "Assistent des Personalfachmanns",
            "Spezialist der Personalverwaltung",
            "Inspektor / Inspektor",
            "Bauingenieur",
            "Ingenieur für zivile Qualitätskontrolle",
            "Ingenieur für zivile Kontrolle",
            "Bauingenieur",
            "Bauprojektleiter",
            "Bauleiter",
            "Bautechniker",
            "Bautechniker",
            "Spezialist für Kontrolle / Infektionskrankheiten",
            "IOS-Entwickler",
            "Spanischlehrer",
            "Statistiklehrer",
            "Statistikspezialist",
            "Business Analyst",
            "Direktor für Marketing und Geschäftsentwicklung",
            "Geschäftsentwicklungsassistent General Manager",
            "Geschäftentwicklungskoordinator",
            "Business Development Manager",
            "Ingenieur für Geschäftsentwicklung",
            "Spezialist für Geschäftsentwicklung",
            "Geschäftsentwicklung und Projektmanager",
            "Arbeitsschutzkoordinator",
            "Arbeitsschutzingenieur",
            "Arbeitsschutztechniker",
            "Spezialist für Arbeitsplatzsicherheit",
            "Baumaschinenbediener",
            "Arbeitsinspektor",
            "Spezialist für Geschäftsplanung",
            "Arbeitsschutzingenieur",
            "Arbeitsschutzpersonal",
            "Arbeitsschutztechniker",
            "Arbeitsschutzspezialist",
            "Arzt am Arbeitsplatz",
            "Business Intelligence Analyst",
            "Business Intelligence Engineer",
            "Business Intelligence-Experte",
            "Business Intelligence Manager",
            "Gebärdensprachlehrer",
            "Gebärdensprachübersetzer",
            "Rekrutierungsassistent Spezialist",
            "Rekrutierungsspezialist",
            "Rekrutierungsmanager",
            "Geschäftsführer",
            "Betriebsingenieur",
            "Italienischlehrer",
            "Export Export Personal",
            "Export Manager importieren",
            "Import Export Verantwortlich",
            "Import Export Spezialist",
            "Wichtiger Manager",
            "Kundenvertreter importieren",
            "Wichtiger Manager",
            "Importspezialist",
            "",
            "Gendarmerie-Unteroffizier",
            "Japanischer Lehrer",
            "Java Software Architect",
            "Java Software Engineer",
            "Java-Software-Spezialist",
            "JCB-Betreiber",
            "Ingenieur für Geodäsie und Photogrammetrie",
            "Geophysiker",
            "Geophysikalischer Ingenieur",
            "Geologe",
            "Geologischer Ingenieur",
            "Geologischer Ingenieur",
            "geotechnischer Ingenieur",
            "",
            "Kabinenleiter",
            "Besatzungsmitglied",
            "Kabinenpersonal",
            "Katastertechniker",
            "Geburtshilfe Krankenschwester",
            "Gynäkologe",
            "Kaffee-Experte",
            "Steward",
            "Kalemie ist",
            "Spezialist für Formenbau",
            "Formenmeister",
            "Formenbauer",
            "Kalibrierungsmanager",
            "Kalibrieringenieur",
            "Kalibriertechniker",
            "Kalibrierungsspezialist",
            "Qualifikationsspezialist",
            "Qualitätsprüfer",
            "Qualitätsdirektor",
            "Qualitätssicherungsmanager",
            "Qualitätssicherungsingenieur",
            "Spezialist für Qualitätssicherung",
            "Analyst für Qualitätskontrolle",
            "Personal für Qualitätskontrolle",
            "Leiter der Qualitätskontrolle",
            "Ingenieur für Qualitätskontrolle",
            "Qualitätskontrollbetreiber",
            "Qualitätskontrollbeauftragter",
            "Chef der Qualitätskontrolle",
            "Steuerungstechniker",
            "Qualitätsmanager",
            "Qualitätsingenieur",
            "Qualitätsspezialist",
            "Qualitätsmanager",
            "Qualitätsmanagement verantwortlich",
            "Steward",
            "Kameramann",
            "Kampagnenspezialist",
            "Kampagnen-Manager",
            "LKW Fahrer",
            "Channel Development Manager",
            "Spezialist für Kanalentwicklung",
            "Beschichtungsmeister",
            "Bodywork Master",
            "Kapitän",
            "Kardiologie Krankenschwester",
            "Kardiologe",
            "Karikaturist",
            "Karriereberater",
            "Kassierer",
            "Kategoriespezialist",
            "Category Manager / Director",
            "Verkäufer",
            "Spezialist für Mehrwertdienste",
            "Gummipressenbetreiber",
            "Skilehrer",
            "Schweißinspektor",
            "Schweißfachingenieur",
            "Schweißtechniker",
            "Ressourcenmaster",
            "Kebab-Meister",
            "Geigenlehrer",
            "Chemotherapie-Krankenschwester",
            "Urban Transformation Master",
            "Baggerbetreiber",
            "Senior Digital Marketing Manager",
            "Senior E-Commerce Einkaufsspezialist",
            "Senior Business Analyst",
            "Senior Business Intelligence Experte",
            "Senior Recruitment Specialist",
            "Senior SAP Consultant",
            "Leitender SAP-Spezialist",
            "Senior Data Analyst",
            "Senior Software Architect",
            "Senior-Software-Entwickler",
            "Senior Software Specialist",
            "Großkundenbetreuer",
            "Chemieingenieur",
            "Chemielehrer",
            "Chemietechniker",
            "Chemietechniker",
            "Chemiker",
            "Spezialist für persönliche Entwicklung",
            "Spezialist für den Schutz personenbezogener Daten",
            "Klimaanlagentechniker",
            "Klinischer Psychologe",
            "KMU-Kundenvertreter",
            "KMU-Portfoliomanager",
            "KMU-Spezialist",
            "Duftspezialist",
            "Pageboy",
            "Kommissar",
            "Konfigurationsingenieur",
            "Portier",
            "Konsolidierungsmanager",
            "Konsul",
            "Bauingenieur",
            "Konstruktoren",
            "Steuerungstechniker",
            "Steuerungs- und Automatisierungstechniker",
            "Regler",
            "Choreograph",
            "Hundetrainer",
            "Kolumnist",
            "Creative Director",
            "Kreditanalyst",
            "Bonitätsspezialist",
            "Spezialist für Kreditvergabe",
            "Kreditspezialist",
            "Kindergärtnerin",
            "Turmdrehkranführer",
            "User Experience-Spezialist",
            "Redaktionsleiter",
            "Unternehmensberater",
            "Direktor für Unternehmenskommunikation",
            "Manager für Unternehmenskommunikation",
            "Assistent für Unternehmenskommunikation",
            "Spezialist für Unternehmenskommunikation",
            "Manager / Direktor für Unternehmenskommunikation",
            "Spezialist für Unternehmensbeziehungen",
            "Firmenkundenvertreter",
            "Corporate Marketing Spezialist",
            "Unternehmensverkaufsberater",
            "Corporate Sales-Manager",
            "Corporate Sales Representative",
            "Corporate Sales Spezialist",
            "Bote",
            "",
            "Laborassistent",
            "Laborpersonal",
            "Laboringenieur",
            "Labor Manager",
            "Labortechniker",
            "Labortechniker",
            "Laminatmeister",
            "Laserschneidoperator",
            "Hafenbetriebspersonal",
            "Linux-Systemspezialist",
            "Linux System Manager",
            "Lader-Bediener",
            "Logo Designer",
            "Logistik-Lagerelement",
            "Logistiklager Verantwortlich",
            "Logistik-Manager",
            "Logistikingenieur",
            "Verantwortlicher Logistikbetrieb",
            "Spezialist für Logistikbetriebe",
            "Spezialist für Logistikplanung",
            "Logistikexperte",
            "",
            "Bergbauingenieur",
            "Bergbautechniker",
            "Bergbauingenieur",
            "Verkäufer",
            "Visual Responsible speichern",
            "Assistant Store Manager",
            "Geschäftsleiter",
            "Verkaufsberater",
            "Geschäftsleiter / Direktor",
            "Autoritätsfahrer",
            "Maschinenenergiemanager",
            "Maschineninspektor",
            "Mitglied der Maschinenmontage",
            "Maschinenbauingenieur",
            "Maschinenbediener",
            "Maschinenmaler",
            "Maschinentechniker",
            "Maschinentechniker",
            "Maschinenbauingenieur",
            "Maschinist",
            "Make-up-Spezialist",
            "Maskenbildner",
            "Hausverwaltung",
            "Finanzanalyst",
            "Finanzberater",
            "Direktor für Finanzangelegenheiten",
            "Koordinator für Finanzangelegenheiten",
            "Finanzchef",
            "Finanzspezialist",
            "Assistent für Finanzangelegenheiten",
            "Finanzspezialist",
            "Finanzmanager",
            "Spezialist für Finanzkontrolle",
            "Finanzberater",
            "Spezialist für Finanzanalyse",
            "Spezialist für Finanzanalyse und Nachrichtendienste",
            "Manager für Finanz- und Verwaltungsangelegenheiten",
            "Kostenkontrollingenieur",
            "Kostenrechnungsspezialist",
            "Materialingenieur",
            "Materialplanungsingenieur",
            "Mammographietechniker",
            "Manikürist",
            "Modell",
            "Markenberater",
            "Brand Director",
            "Markenbotschafter",
            "Markenkommunikationsspezialist",
            "Brand Manager",
            "Markenverantwortlich",
            "Markenvertreter",
            "Markenexperte",
            "Brand Manager / Director",
            "Masseuse",
            "Mathematikingenieur",
            "Mathematiklehrer",
            "Präsident der Versammlung",
            "Medizinischer Berater",
            "Facharzt für Medizinphysik",
            "Media Planning Manager",
            "Spezialist für Medienplanung",
            "Medienspezialist",
            "Manager für mechanische Wartung",
            "Ingenieur für mechanische Wartung",
            "Mechanischer Wartungstechniker",
            "Manager für mechanische Wartung",
            "Maschinenbauingenieur",
            "Mechaniker",
            "Mechaniker",
            "Mechanischer Installationsingenieur",
            "Mechaniker",
            "Ingenieur für Mechatronik",
            "Mechatroniker",
            "Mechatroniker",
            "Mechatronik",
            "Offizier",
            "Manager",
            "Mental Arithmetic Teacher",
            "Kaufmann",
            "Merchandiser Manager",
            "Marmor-Techniker",
            "Marmormeister",
            "Lehrer für Metallarbeiten",
            "Metallographie",
            "Metallurgie- und Materialingenieur",
            "Metallurgischer Ingenieur",
            "Meteorologischer Ingenieur",
            "Texter",
            "Methodeningenieur",
            "Mico",
            "Mihmandar",
            "Mikrobiologischer Analyst",
            "Spezialist für Mikrobiologie",
            "Stellvertreter",
            "Architekt",
            "Architekturdesigner",
            "Architektonischer technischer Maler",
            "Guest Relations Manager",
            "Gastbeauftragter",
            "Entwickler mobiler Anwendungen",
            "Mobilkranführer",
            "Mobile Software Engineer",
            "Spezialist für mobile Software",
            "Möbelmonteur",
            "Moderedakteurin",
            "Modedesigner",
            "Modell",
            "Designer",
            "Assistent Modelist",
            "Moderator",
            "Molekularbiologe",
            "Montagebetreiber",
            "Hypothekenberater",
            "Motorlehrer",
            "Motorentechniker",
            "Motor Kurier",
            "MR-Techniker",
            "Korrespondent",
            "Buchhaltungsassistent",
            "Buchhaltungspersonal",
            "Buchhaltungsleiter",
            "Buchhaltungslehrer",
            "Buchhalter",
            "Spezialist für Buchhaltungsassistenten",
            "Buchhaltungsspezialist",
            "Buchhaltungs- und Finanzmanager",
            "Buchhaltungs- und Finanzbeauftragter",
            "Spezialist für Buchhaltung und Berichterstattung",
            "Rechnungsführer",
            "Reeve",
            "Treuhänder",
            "Küchenchef",
            "Gerichtsvollzieher",
            "Buchbinder Meister",
            "Regieassistent",
            "Ingenieur",
            "Unterstaatssekretär",
            "Kundenberater",
            "Spezialist für Kundenerfahrung",
            "Customer Experience Manager",
            "Kundenservice verantwortlich",
            "Kundendienstvertretung",
            "Customer Relations Officer",
            "Kunden Vertreter",
            "Auftragnehmer",
            "Musiklehrer",
            "",
            "Krankenschwester für Nephrologie",
            "Nephrologe",
            "Spezialist für Nenatologie",
            "Spezialist für Netzwerksicherheit",
            "Netzwerkspezialist",
            "Notar",
            "Notar",
            "Neurologie-Experte",
            "Facharzt für Neurochirurgie",
            "Ingenieur für Kernenergie",
            "Ingenieur für Kernphysik",
            "Nuklearmedizinische Krankenschwester",
            "Nuklearmedizinischer Techniker",
            "",
            "Audiologe",
            "Audiologie-Spezialist",
            "Audiometrietechniker",
            "Audiometriker",
            "Schuldirektor",
            "Vorschullehrer",
            "Ausbilder / Lektor",
            "Wirbelsäulenchirurg",
            "Online-Marketing-Spezialist",
            "Mitarbeiter der Operationsunterstützung",
            "Betriebsleiter",
            "Operations Assistant General Manager",
            "Operations Officer",
            "Betriebsleiter",
            "Operations Manager",
            "Operationschef",
            "Bedienungsmenager",
            "Betriebsleiter / Direktor",
            "Operator",
            "Betreiber Doktor",
            "Optischer Ingenieur",
            "Optiker",
            "Optitex-Betreiber",
            "Spezialist für Organisationsentwicklung",
            "Veranstalter",
            "Dirigent",
            "Forstingenieur",
            "Forstingenieur",
            "Kieferorthopäde",
            "Orthopädische Krankenschwester",
            "Orthopäde",
            "Orthopäde Techniker",
            "Orthopäde",
            "Spezialist für Orthopädie und Traumatologie",
            "Osmanischer Lehrer",
            "Hotelmanager",
            "Busfahrer",
            "Autoklavenbediener",
            "Automatisierungstechniker",
            "Automatisierungstechniker",
            "Automatisierungstechniker",
            "Automobil-Ingenieur",
            "Kfz-Techniker",
            "Spiel Schwester",
            "Spielentwickler",
            "Spieledesigner",
            "Spezialist für Spielesoftware",
            "Spieler",
            "",
            "Lehrer",
            "Fakultätsmitglied",
            "Lehrer",
            "Front Office-Mitarbeiter",
            "Pre-Accounting-Mitarbeiter",
            "Stabschef",
            "Chauffeur",
            "",
            "Verpackungsingenieur",
            "Sanitäter",
            "Konditormeister",
            "Patentingenieur",
            "Patentfachmann",
            "Pathologietechniker",
            "Spezialist für Pathologie",
            "Marktforschungsanalyst",
            "Marktforschungsspezialist",
            "Marktforscher",
            "Marketing-Berater",
            "Marketing-Mitarbeiter",
            "Marketing Assistant General Manager / CMO",
            "Spezialist für Marketingkommunikation",
            "Marketing Manager",
            "Marketingexperte",
            "Marketing Manager / Regieassistent",
            "Pädagoge",
            "Facharzt für Pädiatrie",
            "Facharzt für Pädodontie",
            "Perfusionstechniker",
            "Perfusionisten",
            "Ingenieur für regelmäßige Wartung",
            "Personalleiter",
            "Spezialist für Personalangelegenheiten",
            "Personalleiter",
            "Stabschef",
            "Pestizidspezialist",
            "Petrophysikalischer Ingenieur",
            "Erdölingenieur",
            "Landschaftsarchitekt",
            "Landschaftstechniker",
            "Landschaftsarchitekt",
            "PHP Software Spezialist",
            "Diamant-Qualitätselement",
            "Pilates Instruktor",
            "Pilot",
            "Pianist",
            "Klavierlehrer",
            "Pizza Meister",
            "Planungspersonal",
            "Planungs-Manager",
            "Planungsingenieur",
            "Planungsspezialist",
            "Planungs- und Berichtsspezialist",
            "Außendienstmitarbeiter",
            "Facharzt für Plastische Chirurgie",
            "Kunststoff-Injektionsbetreiber",
            "Pneumatiker",
            "Podologe",
            "Polymeringenieur",
            "Polymerisationsingenieur",
            "Portfoliomanager / Regieassistent",
            "Allgemeinarzt",
            "Drücken Sie Operator",
            "Hersteller",
            "Professor Doktor",
            "Projektassistent",
            "Projektberater",
            "Projektentwicklungsspezialist",
            "Projektsteuerungsingenieur",
            "Projektkoordinator",
            "Projektarchitekt",
            "Projektmanager",
            "Projektingenieur",
            "Projektvertrieb verantwortlich",
            "Projektmanager",
            "Projekttechniker",
            "Projektmanager / Direktor",
            "Promotion-Spezialist",
            "Promoter",
            "Prothetischer Orthesentechniker",
            "Prototyp Ingenieur",
            "Probenmodell",
            "Psychiater",
            "Psychologe",
            "Psychologischer Berater",
            "Psychotherapeut",
            "Tally-Mann",
            "Stanzoperator",
            "",
            "Krankenschwester für Radiologie",
            "Radiologie-Berichterstatter",
            "Radiologietechniker",
            "Radiologietechniker",
            "Radiologie-Spezialist",
            "Strahlentherapie-Techniker",
            "Berichtsspezialist",
            "Reporter",
            "Ingenieur für Schienensysteme",
            "Korrektor",
            "Leitfaden Lehrer",
            "Anleitung und psychologischer Berater",
            "Bühnenmanager",
            "Werbeberater",
            "Werbemanager",
            "Anzeigenvertriebsmitarbeiter",
            "Werbe- und PR-Beauftragter",
            "Ad Writer",
            "Farbanalyst",
            "Farbexperte",
            "Rezeptionist",
            "Kunstlehrer",
            "Restaurantmanager",
            "Restaurierungstechniker",
            "Restaurator",
            "Abteilungsleiter",
            "RF Planungsingenieur",
            "RF Design Engineer",
            "Spezialist für Risikobewertung",
            "Spezialist für Risikoüberwachung",
            "Risikomanager",
            "Risikoingenieur",
            "Risikospezialist",
            "Spezialist für Risikomanagement",
            "Rheumatologe",
            "Röntgentechniker",
            "Röntgentechniker",
            "Lizenzspezialist",
            "Russischlehrer",
            "",
            "Haarpflegespezialist",
            "Haartransplantationsspezialist",
            "Haarstylist",
            "Gesundheitsbeauftragter",
            "Gesundheitspersonal",
            "Gesundheitstechniker",
            "Gesundheitstechniker",
            "Außendienstmitarbeiter",
            "Feldingenieur",
            "Außendienstmitarbeiter",
            "Außendienstmitarbeiter",
            "Feld Verkauf Manager",
            "Außendienstmitarbeiter",
            "Außendienstspezialist",
            "Spezialist für virtuelle Realität",
            "künstlerischer Leiter",
            "Kraftwerksbeauftragter",
            "SAP-Berater",
            "SAP-Support-Spezialist",
            "SAP HR Consultant",
            "SAP Projektmanager",
            "SAP-Spezialist",
            "Einkaufsleiter",
            "Einkaufspersonal",
            "Einkaufsleiter",
            "Einkaufsingenieur",
            "Einkaufsleiter",
            "Einkaufsassistent Spezialist",
            "Handelsfachmann",
            "Verkaufsberater",
            "Spezialist für Vertriebsunterstützung",
            "Verkaufsleiter",
            "Verkäufer",
            "Vertriebsentwicklungsspezialist",
            "Sales Development Manager",
            "Verkaufsleiter",
            "Verkaufsingenieur",
            "Sales Operations Manager",
            "Verkaufsleiter",
            "Sales Operations Specialist",
            "Vertriebsmarketing-Mitarbeiter",
            "Manager für Verkauf und Vertrieb",
            "Vertriebsmarketing-Spezialist",
            "Vertrieb verantwortlich",
            "Außendienstmitarbeiter",
            "Verkaufsexperte",
            "Verkaufs und Marketing Direktor",
            "Vertriebs-und Marketingmanager",
            "Vertriebs- und Marketingfachmann",
            "Schachlehrer",
            "Öffentlicher Ankläger",
            "Seiten-Designer",
            "Ingenieur für digitales Design",
            "Buchhalter",
            "Segment Manager",
            "Sekretär",
            "Drehbuchautor / Drehbuchautor",
            "Keramikingenieur",
            "Keramiktechniker",
            "Keramikmeister",
            "Freiberuflicher Buchhalter",
            "Servicetreiber",
            "Toningenieur",
            "Sprachoperator",
            "Tontechniker",
            "Tontechniker",
            "Sprachexperte",
            "Sprecher",
            "Versandleiter",
            "Reiseberater",
            "Bräutigam",
            "Klassenlehrer",
            "Versicherungsberater",
            "Versicherungsexperte",
            "Versicherungspersonal",
            "Versicherungsmanager",
            "Versicherungsproduzent",
            "Versicherungsspezialist",
            "Versicherungs- und Altersberater",
            "Zyklotron-Ingenieur",
            "Zyklotron-Experte",
            "Bewaffneter Sicherheitsbeauftragter",
            "Simultandolmetscher",
            "Systemanalytiker",
            "System Support Engineer",
            "Experte für Systemunterstützung",
            "Systementwicklungsspezialist",
            "Spezialist für Systemsicherheit",
            "Systemingenieur",
            "Systemspezialist",
            "System- und Netzwerkingenieur",
            "Systemadministrator / Director",
            "SMMM Intern",
            "Solist",
            "Bohringenieur",
            "Bohrtechniker",
            "Sonder",
            "Lehrer für Sozialwissenschaften",
            "Assistent des Wirtschaftsprüfers für soziale Sicherheit",
            "Experte für soziale Sicherheit",
            "Sozialarbeiter",
            "Spezialist für soziale Dienste",
            "Social Media Assistent",
            "Social Media Berater",
            "Social Media Director",
            "Social Media Editor",
            "Social Media Kundenvertreter",
            "Social Media Experte",
            "Social Media Manager",
            "Auditor für soziale Compliance",
            "Soziologe",
            "Sous Chef",
            "Surf Trainer",
            "Landvermesser",
            "Vertragsspezialist",
            "Sporttrainer",
            "Sportansager",
            "Praktikant",
            "Rechtsanwalt",
            "Auszubildende Krankenschwester",
            "Referendar",
            "Statike ist",
            "STEM-Lehrer",
            "Sterilisationsbeauftragter",
            "Sterilisationstechniker",
            "Stilberater",
            "Stylist",
            "Bestandskontrollbeauftragter",
            "Spezialist für Strategie und Geschäftsentwicklung",
            "Spezialist für strategische Planung",
            "Manager für strategische Planung und Geschäftsentwicklung",
            "Wasserballettlehrer",
            "Aquakulturingenieur",
            "Fischtechniker",
            "Offizier",
            "Supervisor",
            "Prozess / Prozessentwicklungsmanager",
            "Prozess / Prozessingenieur",
            "Prozess / Prozesstechniker",
            "Landvermesser",
            "Überwachungstechniker",
            "",
            "Sprachlehrer",
            "Seitenverwalter",
            "Seitenverwalter",
            "Bauleiter",
            "Weinspezialist",
            "Stadtplan",
            "Fahrer / Fahrer",
            "",
            "Sammlungsspezialist",
            "Kollektor",
            "Schmuckdesigner",
            "Mannschaftstrainer",
            "Tankerfahrer",
            "Landwirtschaftlicher Berater",
            "Geschichtslehrer",
            "Designassistent",
            "Gestaltungselement",
            "Design Architekt",
            "Entwicklungsingenieur",
            "Design-Experte",
            "Deckenkranführer",
            "Supply Chain Director",
            "Supply Chain Manager",
            "Versorgungskettenspezialist",
            "Supply Chain Manager",
            "Leutnant",
            "Sicherheitsberater für gefährliche Stoffe",
            "Technisches Zeichenpersonal",
            "Spezialist des technischen Hilfedienstes",
            "Technischer Direktor",
            "Technischer Lehrer",
            "Zeichner",
            "Techniker",
            "Technologen",
            "Technologieberater",
            "Technologiespezialist",
            "Lehrer für Technologie und Design",
            "Textilingenieur",
            "Textildesigner",
            "Textiltechniker",
            "Seilbahnbetreiber",
            "Telefonist",
            "Telekommunikations-Ingenieur",
            "Tele-Sales-Teamleiter",
            "Funker",
            "Tennistrainer",
            "Tennisspieler",
            "Therapeut",
            "Übersetzer / Übersetzer",
            "Werftmanager",
            "Schneider",
            "Testingenieur",
            "Test Automation Engineer",
            "Testspezialist",
            "Medizinischer Biologe",
            "Medizinische Vertreter",
            "Medizinischer Vertriebsmitarbeiter",
            "Medizinisches Sekretariat",
            "Manager für medizinische Beförderung",
            "Vertreter für medizinische Beförderung",
            "Medizintechniker",
            "Medizintechniker",
            "Medizinischer Übersetzer",
            "Arzt / Arzt",
            "LKW Fahrer",
            "Kaufmännischer Assistent General Manager / CCO",
            "Commercial Marketing Manager",
            "Spezialist für kommerzielles Marketing",
            "Commercial Marketing Manager",
            "TOEFL / IELTS Lehrer",
            "Toxikologen",
            "Tonmaister",
            "Topograph",
            "Verkehrsberater",
            "Lokführer / Vatman",
            "Reiseveranstalter",
            "Der Reiseleiter",
            "Turquality-Experte",
            "IVF Krankenschwester",
            "Türkischer Sprach- und Literaturlehrer",
            "Türkischlehrer",
            "Tabakexperte",
            "das",
            "Flugzeugwartungsingenieur",
            "Chef der Flugzeugwartung",
            "Flugzeugwartungstechniker",
            "Flugzeugsicherheitschef",
            "Flugzeugingenieur",
            "Flugzeugsystemingenieur",
            "Flugzeugtechniker",
            "Flugingenieur",
            "Verkehrsingenieur",
            "Manager für internationale Bildungsprogramme",
            "Spezialist für internationale Bildungsprogramme",
            "Spezialist für internationale Beziehungen",
            "Internationaler Marketing Manager",
            "Spezialist für Anwendungsentwicklung",
            "Schlaftechniker",
            "Sergeant",
            "Ernährungsberater",
            "Spezialist",
            "Experte Psychologe",
            "Assistent Spezialist",
            "Langzeitpraktikant",
            "Ü",
            "Bezahlter Lehrer",
            "Produktionspersonal",
            "Produktionsleiter",
            "Fertigungsingenieur",
            "Produktions Leiter",
            "Produktionsplanungsmanager",
            "Produktionsplanungsingenieur",
            "Produktionsplanung Verantwortlich",
            "Spezialist für Produktionsplanung",
            "Produktionsleiter",
            "Produktions- und Planungsingenieur",
            "Urologie / Bevliye Spezialist",
            "Produktentwicklungsingenieur",
            "Spezialist für Produktentwicklung",
            "Produktmanager",
            "Produktdesigner",
            "Produkt Spezialist",
            "Produktmanager / Direktor",
            "",
            "Gouverneur",
            "Validierungsingenieur",
            "Schichtleiter",
            "Schichtleiter",
            "Stellvertretender Lehrer",
            "Steueranalyst",
            "Steuerberater",
            "Steuerprüfer",
            "Assistent des Steuerinspektors",
            "Assistent des Steuerinspektors",
            "Steuerprüfer",
            "Steuerspezialist",
            "Data Warehouse Analyst",
            "Data Warehouse Designer",
            "Data Warehouse-Spezialist",
            "Daten Analyst",
            "Daten Analyst",
            "Datenwissenschaftler",
            "Dateneingabeelement",
            "Datenerfasser",
            "Dateneingabespezialist",
            "Bediener für Datenaufbereitung und -steuerung",
            "Data Mining-Spezialist",
            "Rechenzentrumsingenieur",
            "Rechenzentrumsspezialist",
            "Rechenzentrums-Manager",
            "Datenarchitekt",
            "Dateningenieur",
            "Datenbankprogrammierer",
            "Datenbankspezialist",
            "Datenbankmanager",
            "Produktivitätsmanager",
            "Produktivitätsingenieur",
            "Produktivitätsspezialist",
            "Datenbankingenieur",
            "Tierarzt",
            "Schatzmeister",
            "Videobearbeiter",
            "Videograf",
            "Kranführer",
            "Visa Berater",
            "Sänger",
            "Volleyballtrainer",
            "W.",
            "Webinterface-Entwickler",
            "Web Master",
            "Spezialist für Web-Frontface-Entwicklung",
            "Webprogrammierer",
            "Webdesign-Spezialist",
            "Web-Software-Spezialist",
            "",
            "Schutz schließen",
            "Lean Production Engineer",
            "Lean Manufacturing Spezialist",
            "Ingenieur für künstliche Intelligenz",
            "Bauinspektionsingenieur",
            "Produktions Koordinator",
            "Ingenieur für Strukturanalyse",
            "Konstruktionsingenieur",
            "Oberstleutnant",
            "Assistenzprofessor Doktor / Asst.",
            "Aushilfslehrer",
            "Hilfspersonal im Gesundheitswesen",
            "Life-Coach",
            "Yachtkapitän",
            "Anlageberater",
            "Anlagespezialist",
            "Koordinator für Veröffentlichungen",
            "Verlagsleiter",
            "Chefredakteur",
            "Softwareberater",
            "Software Support Engineer",
            "Software-Support-Spezialist",
            "Software Development Manager",
            "Softwareentwicklungsingenieur",
            "Leiter des Softwareentwicklungsteams",
            "Experte für Softwareentwicklung",
            "Softwarearchitekt",
            "Software Manager",
            "Softwareentwickler",
            "Software Intern",
            "Software-Teamleiter",
            "Software Test Engineer",
            "Leiter des Software-Testteams",
            "Software-Testspezialist",
            "Software Assistant Specialist",
            "Software-Spezialist",
            "Ersatzteillogistik Manager",
            "Segellehrer",
            "",
            "Wirtschaftsprüfer",
            "Beeidigter Übersetzer",
            "Neugeborene Intensivpflegerin",
            "Ingenieur für erneuerbare Energien",
            "Bodendienstmitarbeiter",
            "Lebensmittel-und Getränkemanager",
            "Passagierservice-Beauftragter",
            "Administrative Assistent",
            "Unternehmensberater",
            "Präsident des Verwaltungsrates",
            "Spezialist für Managementsysteme",
            "Assistent des Regisseurs",
            "Wohnheimmanager",
            "Übersee Bildungsberater",
            "MSc Lebensmittelingenieur",
            "Hohe Krankenschwester",
            "Bauingenieur",
            "Hochchemiker",
            "Hochchemiker",
            "Architekt",
            "Kapitän",
            "",
            "Gerichtsbediensteter",
            "Polizei",
            "Fahrer eines gepanzerten Fahrzeugs",
            "Geistig behinderter Lehrer",
            "Chain Stores Assistant Manager",
            "Filialleiter",
            "Agraringenieur",
            "Landtechniker",
            "Landtechniker",
            "Agraringenieur",
            "Landwirtschaftlicher Berater",
            "Landwirtschaftlicher Einkaufsspezialist",
            "Zootechniker",
            "Zumba Instructor",
            "",
            "3D Animator",
            "3D-Zeichenlehrer",
            "3D-Modellierungsspezialist",
            "3D-Messoperator",
            "Verantwortliches 3D-Design"
    };
}
